export const mockDashboard = [
  {
    name: 'JT',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: -1.6,
    investment: 53430463,
    daysRunning: 3,
    tradingStrategy: 1,
    algoTradingPlanID: 332,
  },
  {
    name: 'Finance',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: 6,
    investment: 234320,
    daysRunning: 2,
    tradingStrategy: 3,
    algoTradingPlanID: 234,
  },
  {
    name: 'JT',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: -1.6,
    investment: 53430463,
    daysRunning: 3,
    tradingStrategy: 1,
    algoTradingPlanID: 332,
  },
  {
    name: 'Finance',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: 6,
    investment: 234320,
    daysRunning: 2,
    tradingStrategy: 3,
    algoTradingPlanID: 234,
  },
  {
    name: 'JT',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: -1.6,
    investment: 53430463,
    daysRunning: 3,
    tradingStrategy: 1,
    algoTradingPlanID: 332,
  },
  {
    name: 'Finance',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: 6,
    investment: 234320,
    daysRunning: 2,
    tradingStrategy: 3,
    algoTradingPlanID: 234,
  },
  {
    name: 'JT',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: -1.6,
    investment: 53430463,
    daysRunning: 3,
    tradingStrategy: 1,
    algoTradingPlanID: 332,
  },
  {
    name: 'Finance',
    market: 'BTC/USDT',
    exchange: 'Binance',
    profitLoss: 6,
    investment: 234320,
    daysRunning: 2,
    tradingStrategy: 3,
    algoTradingPlanID: 234,
  },
];
