export const historyData = [
  {
    name: 'bot15',
    market: 'BTC',
    exchange: 'Binance',
    investment: 3451048.04,
    profitLoss: 2.5,
    daysRunning: 2,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 435,
  },
  {
    name: 'bot16',
    market: 'ETH',
    exchange: 'Ethereum',
    investment: 2306.06,
    profitLoss: -1.3,
    daysRunning: 1,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 436,
  },
  {
    name: 'bot17',
    market: 'BTC',
    exchange: 'Binance',
    investment: 3451048.04,
    profitLoss: 2.5,
    daysRunning: 2,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 437,
  },
  {
    name: 'bot18',
    market: 'ETH',
    exchange: 'Ethereum',
    investment: 2306.06,
    profitLoss: -1.3,
    daysRunning: 1,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 438,
  },
  {
    name: 'bot19',
    market: 'BTC',
    exchange: 'Binance',
    investment: 3451048.04,
    profitLoss: 2.5,
    daysRunning: 2,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 439,
  },
  {
    name: 'bot20',
    market: 'ETH',
    exchange: 'Ethereum',
    investment: 2306.06,
    profitLoss: -1.3,
    daysRunning: 1,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 440,
  },
  {
    name: 'bot21',
    market: 'BTC',
    exchange: 'Binance',
    investment: 3451048.04,
    profitLoss: 2.5,
    daysRunning: 2,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 441,
  },
  {
    name: 'bot22',
    market: 'ETH',
    exchange: 'Ethereum',
    investment: 2306.06,
    profitLoss: -1.3,
    daysRunning: 1,
    tradingStrategy: 'Grid',
    algoTradingPlanID: 442,
  },
];
